# Generated by Django 5.0.6 on 2024-07-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooks', '0002_teamcook_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='single',
            name='password',
            field=models.CharField(default='default_password', max_length=100),
        ),
        migrations.AddField(
            model_name='teamcook',
            name='password',
            field=models.CharField(default='default_password', max_length=100),
        ),
    ]
