# Generated by Django 5.0.6 on 2024-07-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooks', '0003_single_password_teamcook_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='single',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
    ]
