# Generated by Django 5.0.6 on 2024-07-23 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooks', '0005_single_desc_teamcook_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='single',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='teamcook',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
