from django.contrib import admin
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('service/', views.service, name='service'),
    path('menu/', views.menu, name='menu'),
    path('booking/', views.booking, name='booking'),
    path('testimonial/', views.testimonial, name='testimonial'),
     path('contact/', views.contact, name='contact'),
    path('team/', views.team, name='team'),
    path('details/', views.details, name='details'),
    path('signup/', views.handleSignUp, name='handleSignUp'),
    path('updatesingle/', views.updatesingle, name='updatesingle'),
    path('updateteam/', views.updateteam, name='updateteam'),
    path('viewProfile/<int:id>/', views.viewProfile, name='viewProfile'),
    path('login/', views.handleLogin, name='handleLogin'),
    path('handleCook/', views.handleCook, name='handleCook'),
    path('handleTeam/', views.handleTeam, name='handleTeam'),
    path('logout/', views.handleLogout, name='handleLogout'),
    path('generate_invoice/<int:booking_id>/', views.generate_invoice, name='generate_invoice'),
    path('cookalready/', views.cookalready, name='cookalready'),
    path('handleReg/', views.handleReg, name='handleReg'),
    path('cook/', views.cook, name='cook'),
    path('teamreg/', views.teamreg, name='teamreg'),
    path("search/",views.search,name="search"),
    path("checkout/",views.checkout,name="checkout"),
    path("payment/",views.payment,name="payment"),
    path("bookView/",views.bookView,name="bookView"),
    path("cookView/<int:id>/",views.cookView,name="cookView"),
    path('singlecookdetails/<int:singlecook_id>/', views.singlecookdetails, name='singlecookdetails'),
    path('teamdetails/<int:teamcook_id>/', views.teamdetails, name='teamdetails'),
    path('success/', views.success, name='success'),
    path('download_file/', views.download_file, name='download_file'),
]
